builders:
  enume:
    import: "package:enume_generator/builder.dart"
    builder_factories: ["enumeBuilder"]
    build_extensions: { ".dart": ["g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]