name: enume_generator
description: Enume generator - useful enum extensions for dart
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  enume:
    path: ../enume

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
