name: enume_generator
description: Enume - collection of useful enum extensions for dart. Like a Name-Method and TypedEnums for the ability to assign specific values each of the enumerated types.
version: 1.0.0
homepage: https://github.com/Ladegeraet/Enume

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1
  enume: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
